# Generated by Django 5.0.6 on 2024-06-25 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OngoingMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roomId', models.CharField(max_length=200)),
                ('playerCount', models.IntegerField(default=1)),
                ('ready', models.BooleanField(default=False)),
                ('player1', models.CharField(max_length=200)),
                ('player2', models.CharField(max_length=200)),
                ('player1Paddle_y', models.FloatField(default=0)),
                ('player2Paddle_y', models.FloatField(default=0)),
                ('goalsPlayer1', models.IntegerField(default=0)),
                ('goalsPlayer2', models.IntegerField(default=0)),
                ('ball_x', models.FloatField(default=0)),
                ('ball_y', models.FloatField(default=0)),
            ],
        ),
    ]
