# Generated by Django 5.0.6 on 2024-05-29 09:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matchId', models.IntegerField()),
                ('matchName', models.CharField(max_length=50)),
                ('matchDate', models.DateTimeField()),
                ('matchWinnerScore', models.IntegerField()),
                ('matchLoserScore', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=50)),
                ('avatar', models.ImageField(upload_to='avatars/')),
                ('friendList', models.ManyToManyField(blank=True, to='api.user')),
                ('matches', models.ManyToManyField(blank=True, to='api.match')),
            ],
        ),
        migrations.AddField(
            model_name='match',
            name='matchLoser',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='match_loser', to='api.user'),
        ),
        migrations.AddField(
            model_name='match',
            name='matchWinner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='match_winner', to='api.user'),
        ),
    ]
