# Generated by Django 5.0.6 on 2024-06-18 12:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(upload_to='api/static/avatars/')),
                ('friendList', models.ManyToManyField(blank=True, to='api.account')),
                ('matches', models.ManyToManyField(blank=True, to='api.match')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='match',
            name='matchLoser',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='match_loser', to='api.account'),
        ),
        migrations.AlterField(
            model_name='match',
            name='matchWinner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='match_winner', to='api.account'),
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('messageId', models.IntegerField()),
                ('messageContent', models.CharField(max_length=500)),
                ('messageDate', models.DateTimeField()),
                ('messageReceiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_receiver', to='api.account')),
                ('messageSender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_sender', to='api.account')),
            ],
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
