# Generated by Django 5.0.6 on 2024-06-27 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_account_alter_match_matchloser_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='messageId',
        ),
        migrations.AddField(
            model_name='account',
            name='pingUrl',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='account',
            name='receivedMessages',
            field=models.ManyToManyField(blank=True, related_name='received_messages', to='api.message'),
        ),
        migrations.AddField(
            model_name='account',
            name='sentMessages',
            field=models.ManyToManyField(blank=True, related_name='sent_messages', to='api.message'),
        ),
    ]
