# Generated by Django 5.0.6 on 2024-06-27 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_message_messageid_account_pingurl_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='messageDate',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
