version: '3'

services:
  flow:
    build: ./flow_container
    ports:
      - "8000:8000"
    env_file:
      - ./.env
    depends_on:
      - db
    restart: always
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: ${SQL_USER}
      POSTGRES_PASSWORD: ${SQL_PASSWORD}
      POSTGRES_DB: ${SQL_DATABASE}
    restart: always
    pull_policy: always